# Generated by Django 5.0.1 on 2024-02-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ath', '0002_remove_student_image_student_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='student_images/'),
        ),
    ]
